Revert "bluetooth HID integration"
This reverts commit 03177866c3e1360915d3daccd62e3ab14473f547.

This commit was backed out pending the resolution of the following build error
for TI816x:

frameworks/base/services/java/com/android/server/SystemServer.java:64: package com.ti.omap.omap_mm_library does not exist
import com.ti.omap.omap_mm_library.UiCloningService;
                                  ^
frameworks/base/services/java/com/android/server/SystemServer.java:142: cannot find symbol
symbol  : class UiCloningService
location: class com.android.server.ServerThread
        UiCloningService uiCloning = null;
        ^
frameworks/base/services/java/com/android/server/SystemServer.java:479: cannot find symbol
symbol  : class UiCloningService
location: class com.android.server.ServerThread
                        uiCloning = new UiCloningService(context);
                                        ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors
make: *** [out/target/common/obj/JAVA_LIBRARIES/services_intermediates/classes-full-debug.jar] Error 41