Revert "VideoView changes to handle Dynamic display"
This reverts commit 57f92c95bfc6c01e603baf93e94951720f58f3bd.

This commit was backed out pending the resolution of the following build error
for TI816x:

target Java: framework (out/target/common/obj/JAVA_LIBRARIES/framework_intermediates/classes)
frameworks/base/core/java/android/widget/VideoView.java:46: package com.ti.omap.omap_mm_library does not exist
import com.ti.omap.omap_mm_library.OmapMMLibrary;
                                  ^
frameworks/base/core/java/android/widget/VideoView.java:58: cannot find symbol
symbol  : class OmapMMLibrary
location: class android.widget.VideoView
    private OmapMMLibrary mOmapMMHandle = null;
            ^
frameworks/base/core/java/android/widget/VideoView.java:192: cannot find symbol
symbol  : class OmapMMLibrary
location: class android.widget.VideoView
            mOmapMMHandle = new OmapMMLibrary();
                                ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors
make: *** [out/target/common/obj/JAVA_LIBRARIES/framework_intermediates/classes-full-debug.jar] Error 41